Format generated files

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,8 +1,9 @@
 #!/bin/sh
 # Run build_runner and stage any changes
 dart run build_runner build --delete-conflicting-outputs
-if [ $? -ne 0 ]; then  
-  echo "build_runner failed. Aborting commit."  
-  exit 1  
-fi  
+if [ $? -ne 0 ]; then
+  echo "build_runner failed. Aborting commit."
+  exit 1
+fi
+find lib -name \*.g.dart | xargs dart format
 git add .
